```{r}
library(ProjectTemplate); load.project()


```

# Basic exploration
```{r}
str(rdyads)
names(rdyads)
rdyads$X

head(rdyads)
# General description of dataset
Hmisc::describe(rdyads[,4:ncol(rdyads)])

# * Four leagues in England, France, Germany and Spain
# * Skim colour is skewed with on around 16% in the 4 or 5 zone; There's a question about how to code this core predictor
# * 11 different detailed positions and 4 general positions

hist(rdyads$PlayerHeightCM)
# * Height is normally distributed


# check the one club/league/skincol/etc per player assumption (it's true)
for (i in names(rdyads)) {
    print(i)
    print(table(aggregate(rdyads[, i], list(rdyads$PlayerID), function(X) length(unique(X)))[,2]))
}


# check ref features (refs referee in multiple leagues)
for (i in names(rdyads)) {
    print(i)
    print(table(aggregate(rdyads[, i], list(rdyads$RefereeID), function(X) length(unique(X)))[,2]))
}


# number of matches  per combination
hist(rdyads$Matches)
table(rdyads$Matches)
x <- data.frame(table(rdyads$Matches))
x$Var1 <- as.numeric(x$Var1)
x$combined <- x$Var1 * x$Freq
x$FreqProp <- x$Freq / sum(x$Freq)
x$combinedProp <- x$combined / sum(x$combined)
round(x, 3)

# * distribution of matches is very skewed
# * Although it is less so the case at the match level; e.g., while the interaction rows are based on a single match, matches in general are involve player and refs who will eventually meet 2 or more times 82% of the time.

# What is a YellowRed?
table(YellowRed=rdyads$YellowRed, RedCards=rdyads$RedCards)
table(YellowRed=rdyads$YellowRed, YellowCards=rdyads$YellowCards)
# I thought it might have been a second yellow card that results in being asked to leave the ground
# However, this would only make sense if the first yellow card in didn't count in the yellowcard or redcard leger.

```




```{r}
# number of player IDs
length(unique(rdyads$PlayerID))

# number of dyads per player
length(unique(rdyads$RefereeID))
```

There are a little over two thousand refs and two thousand players.


```{r}
# a quick look at the core research question
summary(lm(RedCardsProp ~ SkinCol, rdyads))
summary(lm(RedCardsProp ~ SkinCol, rdyads, weights=Matches))
summary(lm(YellowCardsProp ~ SkinCol, rdyads))
summary(lm(YellowRedProp ~ SkinCol, rdyads))

plot(aggregate(rdyads$RedCardsProp, list(rdyads$SkinCol), mean, na.rm=TRUE))
plot(aggregate(rdyads$YellowCardsProp, list(rdyads$SkinCol), mean, na.rm=TRUE))
plot(aggregate(rdyads$YellowRedProp, list(rdyads$SkinCol), mean, na.rm=TRUE))


aggregate(rplayers$RedCardsSumProp, list(rplayers$SkinCol), mean, na.rm=TRUE)
aggregate(rplayers$YellowCardsSumProp, list(rplayers$SkinCol), mean, na.rm=TRUE)
summary(lm(RedCardsSumProp ~ SkinCol, rplayers))

summary(lm(RedCardsSumProp ~ factor(SkinCol), rplayers[rplayers$MatchesSum > 100, ]))
```

# Examination of the players dataset
```{r}
# general distribution of redcard proportions
plot(density(rplayers$MatchesSum))
plot(density(rplayers[ rplayers$MatchesSum > 50,'RedCardsSumProp']))
plot(density(rplayers[ rplayers$MatchesSum > 100,'RedCardsSumProp']))
plot(density(rplayers[ rplayers$MatchesSum > 150,'RedCardsSumProp']))
plot(density(rplayers[ rplayers$MatchesSum > 200,'RedCardsSumProp']))
# the distribution of redcards appears to be bimodal or possibly even trimodal
# some never get red flags, another mode exists around 0.5%, and a final small hump seems to be between 1.5 and 2%.

# one challenges is going to be the rare occurrence of red flags
plot(RedCardsSumProp~MatchesSum, rplayers)
# * the above plot shows lines indicating the effect of 1, 2,  or 3 flags over match counts
# * I.e., what shrinkage should be used or how should this be incorporated into the model


# League by red cards
boxplot(RedCardsSumProp ~ League_Country, rplayers)
aggregate(RedCardsSumProp ~ League_Country, rplayers, mean)
summary(lm(RedCardsSumProp ~ League_Country, rplayers))
# * first impressions are that France gives out more red cards

# Position
boxplot(RedCardsSumProp ~ Position, rplayers[rplayers$MatchesSum > 100 , ])
aggregate(RedCardsSumProp ~ Position, rplayers[rplayers$MatchesSum > 100 , ], mean)
summary(lm(RedCardsSumProp ~ Position, rplayers[rplayers$MatchesSum > 100 , ]))
# Although defence looks like it gets more red flags than other areas
# but the difference might not be signficant or at least it would require further analysis.

boxplot(RedCardsSumProp ~ Position_Detailed, rplayers[rplayers$MatchesSum > 100 , ])
aggregate(RedCardsSumProp ~ Position_Detailed, rplayers[rplayers$MatchesSum > 100 , ], mean)
summary(lm(RedCardsSumProp ~ Position_Detailed, rplayers[rplayers$MatchesSum > 100 , ]))

# year of birth/age
with(rplayers[rplayers$MatchesSum > 100 , ], scatter.smooth(BirthY, RedCardsSumProp))
# * nothing much


with(rplayers[rplayers$MatchesSum > 100 , ], scatter.smooth(BirthY, RedCardsSumProp))

with(rplayers[rplayers$MatchesSum > 100 , ], scatter.smooth(YellowCardsSumProp, RedCardsSumProp))

# There is an association between prop yellow cards and prop red cards

with(rplayers[rplayers$MatchesSum > 50 , ], scatter.smooth(MatchesSum, RedCardsSumProp))
# * slight hint that the proprtion might go up for people with more matches

with(rplayers[rplayers$MatchesSum > 100 , ], scatter.smooth(PlayerHeightCM, RedCardsSumProp))

# club
x <- aggregate(RedCardsSumProp ~ Club, rplayers[rplayers$MatchesSum > 100 , ], mean)
plot(density(x[,2]))
# density of cards per club is fairly normal with a couple of little bumps like the player distributions
summary(lm(RedCardsSumProp ~ Club, rplayers[rplayers$MatchesSum > 100 , ]))


# examination of skin colour
plot(table(rplayers$SkinCol))
round(prop.table(table(rplayers$Position, rplayers$SkinCol),1), 2)
# perhaps  strikers are more likely to have darker skin
round(prop.table(table(rplayers$League_Country, rplayers$SkinCol),1), 2)
# France has the most black players followed by England; Germany and S

# quick examination of the country by skin colour interaction
summary(lm(RedCardsSumProp ~ I(SkinCol>3)*League_Country, rplayers[rplayers$MatchesSum > 100, ]))
summary(lm(RedCardsSumProp ~ I(SkinCol>3)*League_Country, rplayers[rplayers$MatchesSum > 50, ]))
summary(lm(RedCardsSumProp ~ I(SkinCol>3)*League_Country, rplayers))

# Matches
with(rplayers[rplayers$MatchesSum > 20, ], scatter.smooth(log(MatchesSum), RedCardsSumProp))

with(rplayers[rplayers$MatchesSum > 20, ], scatter.smooth(GoalsSumProp, RedCardsSumProp))

head(rrefs)
table(rrefs$RefCountryID, )
```


### Ref database
```{r}
head(rrefs)

plot(density(log(rrefs$MatchesSum, 10)))
plot(density(rrefs[rrefs$MatchesSum > 100, "RedCardsSumProp"]))
plot(density(rrefs[rrefs$MatchesSum > 200, "RedCardsSumProp"]))
plot(density(rrefs[rrefs$MatchesSum > 300, "RedCardsSumProp"]))
plot(density(rrefs[rrefs$MatchesSum > 400, "RedCardsSumProp"]))
table(rrefs$RedCardsSum)
table(rrefs[rrefs$MatchesSum > 200, "RedCardsSum"])
table(rrefs[rrefs$MatchesSum > 100, "RedCardsSum"])
round(prop.table(table(rrefs[rrefs$MatchesSum > 100, "RedCardsSum"])), 3)

# * I guess the density reflects the fact that a lot of referees never give out a red card in their career
# * Including refs just with More games seems to move towards a more normal distribution



```

### Referee Country database
```{r}
# understanding of 
table(rcountries$nIAT)
plot(density(na.omit(rcountries$seIAT)))
aplot(sqrt(rcountries$nIAT), rcountries$seIAT)

plot(density(na.omit(rcountries$meanIAT_RefCountry)))
plot(density(na.omit(rcountries$meanExp_RefCountry)))
plot(meanIAT_RefCountry ~ meanExp_RefCountry, rcountries)


plot(density(log(rcountries$MatchesSum, 10)))
sum(rcountries$MatchesSum >1000)
plot(density(rcountries[ rcountries$MatchesSum > 1000, 'RedCardsSumProp']))
```


# Very basic exploration of models
```{r}
fit <- glm(cbind(RedCards, Matches - RedCards) ~ SkinCol, family=binomial, data=rdyads)
head(rdyads)
summary(fit)

logit2pi <-function (x)  exp(x) / (1 + exp(x))
pred <- coef(fit)[1] + coef(fit)[2] * 1:5
logit2pi(pred)

head(rdyads)
sum(rdyads$RedCards) /   sum(rdyads$Matches)
           
fit


```




